config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    match '/users/:id', :to => 'users#show',    :as => :user,         :via => :get
    match '/users', :to => 'users#index',    :as => :users,         :via => :get
    match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete

    resources :students
    resources :student_responses, only: [:create,:new]
    # resources :tags, except: [:show]
    resources :contents, except: [:index, :show]

    get 'tags/:tag', to: 'static_pages#home', as: 'tugg'

    root :to => "static_pages#home"

    get 'users/:id/contents/summary_index', to: 'contents#summary_index', as: "summary_index"

    match '/help', to: "static_pages#help", via: 'get'
    match '/about', to: "static_pages#about", via: 'get'
    match '/contact', to: "static_pages#contact", via: 'get'

    get 'students/:id/show_response' => "students#show_response", as: "show_response"
    get 'students/:id/show_summary' => "students#show_summary", as: "show_summary"
    get 'students/:id/show_selected' => "students#show_selected", as: "show_selected"

    match '/sign_in_guest', to: "application#create_guest_user", via: 'get'

end

app/models/content.rb
class Content < ActiveRecord::Base

    scope :updated,   ->   { order('updated_at DESC') }
    scope :by_height, ->   { order('height DESC') }
    scope :belongs_to_user, ->(userid) { where(['contents.user_id = ? OR is_public = ?', userid, 'true']) }
    # scope :visible_to_admin, -> {where(['is_public=?', 'true'])}
    # same as belongs_to_user hence not DRY but keeping it separate for the time being
    scope :visible_to_admin, -> (userid) { where(['contents.user_id = ? OR is_public = ?', userid, 'true']) }

    paginates_per 12

    belongs_to :user
    has_many :taggings, :dependent => :destroy

    has_many :tags, through: :taggings, :dependent => :destroy
    has_many :student_responses, through: :taggings

    has_attached_file :image, :styles => { :original => ["100%", :jpg], :thumb => ["100x100#", :jpg] },
                                        :storage => :s3,
                                        :s3_credentials => {
                                            :bucket => ENV['S3_BUCKET_NAME'],
                                            :access_key_id => ENV['AWS_ACCESS_KEY'],
                                            :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                                        },
                                        :path => '/:class/:attachment/:id_partition/:style/:filename',
                                        :url => ':s3_domain_url'

    validates_attachment :image, :presence => true

    validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/pjpeg',
                                   'image/jpg', 'image/png', 'image/gif'], :message => "Image has to be in a valid format: only JPG, PNG, GIF, or JPEG is allowed."

    validates_attachment :image, :size => {:in => 0..2.megabytes, :message => "Image must be less than 2 MB in size."}

    validate :tags_present

    before_save :extract_dimensions

    serialize :dimensions

    def matching_taggings
        taggings.map(&:id).join(', ')
    end

    # currently, not being used
    # def self.tagged_with(name)
    #     Tag.find_by_name!(tagname).contents
    # end

    def self.tag_counts(userid)
        Tag.joins(:contents).where(['contents.user_id = ? OR contents.is_public = ?', userid, 'true']).
            select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("tags.id")
    end

    def self.select_tags(userid)
        Tag.joins(:contents).where(['contents.user_id = ? OR contents.is_public = ?', userid, 'true']).
            select("tags.*").joins(:taggings).group("tags.id")
    end

    def tag_list
        tags.map(&:tagname).join(", ")
    end

    def tag_list=(tagnames)
        tagnames.downcase!
        tagnames = tagnames.split(',').collect(&:strip).uniq.join(',')
        self.tags = tagnames.split(",").map do |t|
            Tag.where(tagname: t.strip).first_or_create!
        end
    end

    # Helper method to determine whether or not an attachment is an image.
    # @note Use only if you have a generic asset-type model that can handle different file types.
    def image?
        image_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}
    end

    def content_public_as_string
        self.is_public ? "Yes" : "No"
    end

    private

        def extract_dimensions
            return unless image?
            tempfile = image.queued_for_write[:original]
            unless tempfile.nil?
                geometry = Paperclip::Geometry.from_file(tempfile)
                self.dimensions = [geometry.width.to_i, geometry.height.to_i]
                self.height = geometry.height.to_i
            end
        end

        def tags_present
            if tag_list.empty?
                errors.add(:image, "tag labels must be present")
            end
        end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

    include ContentsHelper

    before_filter :authorized_user?, only: [:new]
    before_action :set_content, only: [:show, :edit, :update, :destroy]
    skip_before_filter :verify_authenticity_token, :only => :create
    before_action :authorized_as_admin_or_not, only: [:destroy, :update]

    def summary_index
        if current_user.admin
            @contents = Content.visible_to_admin(current_user.id)
        else
            @contents = current_user.contents
        end
    end

    def index
    end

    def show
        @content = Content.find(params[:id])
    end

    def new
        @content = current_user.contents.new(params[:content])
    end

    def edit
        @content = Content.find(params[:id])
    end

    def create
        @content = current_user.contents.build(content_params)

        respond_to do |format|
            if @content.save
                format.html { redirect_to :back }
                format.js
            else
                flash[:alert] = "There was a problem uploading your image: #{errors_helper(@content)}"
                format.html {redirect_to :back}
                format.js
            end
        end
    end

    def update
        respond_to do |format|
            if @content.update(content_params)
                format.html { redirect_to @content }
                format.json { render :show, status: :ok, location: @content }
                format.js { render :js => "window.location.replace('#{url_for(:controller => :contents, :action => :summary_index)}');" }
            else
                format.html { render :edit }
                format.json { render json: @content.errors, status: :unprocessable_entity }
                format.js
            end
        end
    end

    def destroy
        @content.destroy
        respond_to do |format|
            format.html { redirect_to :back, notice: 'Image was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
        def set_content
            @content = Content.find(params[:id])
        end

        def authorized_user?
            if current_user.guest?
                respond_to do |format|
                    format.js { render :js => 'alert("Sorry, but you are not authorized to upload images."+
                        "\n\n"+"Please do sign up first!");' }
                end
            end
        end

        def authorized_as_admin_or_not
            if current_user.admin
                @content = Content.find(params[:id])
            else
                @content = current_user.contents.find_by(:id => params[:id])
                redirect_to root_url if @content.nil?
            end
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def content_params
            params.require(:content).permit(:ctype, :is_public, :dblink, :user_id, :image, :tag_list)
        end

end

app/helpers/contents_helper.rb
module ContentsHelper

    def errors_helper(content)
        content.errors[:image].map{|i| i}.join(" ")
    end
end

app/views/contents/_content.html.erb
<%= image_tag content.image.url(:thumb) %>

app/views/contents/_modal_form.html.erb
<%= form_for current_user.contents.new(params[:content]), :html => { :multipart => true }  do |f| %>

  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" align="center">Upload image</h4>
      </div>

        <div class="modal-body">

            <%= f.text_field :tag_list %>

            <div class = "form-group">
                <label> Select </label>
                <%= f.file_field :image %>
            </div>

            <div class = "checkbox">
                <label>
                    <%= f.check_box :is_public %> Check if public
                </label>
            </div>

                <%= f.hidden_field :user_id, :value => current_user.id %>

        </div>

        <div class="modal-footer">
            <div class="row text-center">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                    <%= f.submit "Save", class: "btn btn-primary btn-sm", name: "add_column" %>
            </div>
        </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

<% end %>

app/views/contents/_new.html.erb
<%= render 'form' %>

app/views/contents/_save.js.erb
<% if @content.errors.any? %>
    $("#modal-body").prepend("<%= escape_javascript(render 'shared/messages', object: @content) %>");
<% else %>
    $("#content-modal").modal("hide");
<% end %>

app/views/contents/create.js.erb
<%= render "save" %>

app/views/contents/edit.html.erb
<h1>Editing content</h1>

<%= render 'form' %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/edit.js.erb
$("#content-modal-title").html("Editing image");

$("#modal-body").html("<%= escape_javascript(render 'form') %>")
$("#content-modal").modal("show")

app/views/contents/index.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-10" role="main">
            <div id="contents">
                <div class = "masonry-container">
                    <% @contents.each do |content| %>
                        <% if content.image.exists?(:original) %>
                            <div class = "masonry-item" >
                                <%= image_tag content.image.url(:original) %>
                            </div>
                        <% else %>
                            <% content.destroy! %>
                        <% end %>
                    <% end %>
                </div>
            </div>
            </br>
            </br>
            </br>
        </div>
        <div class="col-xs-2 fixed">
            <h4> Tagged emotions </h4>
            </br>
            <div id="tag_cloud">
                <% tag_cloud Content.tag_counts(current_user.id), %w{s m l} do |tag, css_class| %>
                    <%= link_to tag.tagname, tugg_path(tag.tagname), class: css_class %>
                <% end %>
            </div>
        </div>
    </div>
</div>

<%= paginate @contents %>

app/views/contents/index.js.erb
$("#contents").append("<tbody class='page'><%= escape_javascript(render(@contents)) %></tbody>");

app/views/contents/new.js.erb
$("#content-modal-title").html("Upload an image");
$("#modal-body").html("<%= escape_javascript(render 'new') %>")
$("#content-modal").modal("show")

$('#content_is_public').on('change', function() {
    if (this.checked)
    {
        var dial =  "<div><p><br />All content set to public will only be available for editing by admin.</p></div>";

        $(dial).dialog({
            title: 'Reminder',
            autoOpen: true,
            width: 550,
            resizable: false,
            buttons: {
                OK: function () {
                    $(this).dialog("close");
                }
            },
                close: function (event, ui) {
                    $(this).remove();
            }
        }).parent().appendTo($("#content-modal"));

        $(".ui-dialog-buttonpane").append("<p class='addendum'><span>Please see <b>About</b> section.</span></p>");
        $(".ui-dialog").css({'top': 176});
    }
});

app/views/contents/show.html.erb
<p>
  <strong>Type:</strong>
  <%= @content.ctype %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @content.is_public %>
</p>

<p>
  <strong>Dblink:</strong>
  <%= @content.dblink %>
</p>

<p>
  <strong>User:</strong>
  <%= @content.user_id %>
</p>
<p>
    <%= image_tag @content.image.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_content_path(@content) %> |
<%= link_to 'Back', root_path, "data-no-turbolink" => true %>

app/views/contents/summary.html.erb
<div id="myCarousel" class="carousel slide" >
    <div class="carousel-inner" >
        <% @contents.each_with_index do |content, index| %>
                <div class="item <% if index == 0 %> active <% end %> id<%=index%> ">

                    <a href='<%= content_path(content) %>'>
                        <%= image_tag content.image.url(:thumb) %>
                    </a>
                    <div class="carousel-caption">
                        <div class = 'bs-example'>
                            <div class="btn-toolbar" role="toolbar">


                                <%= form_for content do |f| %>
                                    <% 1.upto(10) do |c| %>

                                        <%#= f.hidden_field :ctype, :value => c %>
                                        <%#= f.submit c, { :value => c, :class => "btn btn-primary btn-xs"} %>

                                    <% end %>

                            <% end %>

                        </div>

                        </div>

                    </div>

                </div>

        <% end %>
    </div>

    <a class="left carousel-control" href="#myCarousel" data-slide="prev" data-interval="false">
        <%= image_tag 'carousel-arrow-left-hover.png', :class => "chevron chevron-left" %>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next" data-interval="false">
        <%= image_tag 'carousel-arrow-right-hover.png', :class => "chevron chevron-right" %>
        <!-- <img class="chevron chevron-right" src="http://www.lutheranworld.org/sites/all/themes/custom/lwf/images/carousel-arrow-right-hover.png" /> -->
    </a>

</div><!-- /.carousel -->

</br>
</br>

app/views/contents/summary_index.html.erb
<h2>Your images</h2>

<div class="row">
    <div class = "col-sm-6 col-sm-offset-3" >
        <table class='table table-striped' id="table-list-images">
          <thead>
            <tr>
              <th class="col-sm-3">Image</th>
              <th class="col-sm-2">Tags</th>
              <th class="col-sm-1">Public?</th>
                <% if current_user.admin %>
                    <th class="col-sm-1">User email</th>
                <% end %>
              <th colspan="2" class="col-sm-1"></th>
            </tr>
          </thead>

          <tbody>
            <% @contents.each do |content| %>
              <tr>
                <td><%= image_tag content.image.url(:thumb) %></td>
                <td><%=raw content.tags.map(&:tagname).map { |t| t }.join(', ') %></td>
                <td><%= content.content_public_as_string %></td>
                <% if current_user.admin %>
                    <td><%=User.find(content.user_id).email%></td>
                <% end %>
                <% if content.is_public %>
                    <% if current_user.admin %>
                        <td align="center"><%= link_to 'Edit', edit_content_path(content), remote: true, :class => 'btn btn-primary btn-xs' %></td>
                        <td align="center"><%= link_to 'Del', content, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-xs" %></td>
                    <% else %>
                        <td colspan="2" align="center"> <%= link_to 'Email Admin', contact_path, :class => 'btn btn-success btn-xs' %> </td>
                    <% end %>
                <% else %>
                    <td align="center"><%= link_to 'Edit', edit_content_path(content), remote: true, :class => 'btn btn-primary btn-xs' %></td>
                    <td align="center"><%= link_to 'Del', content, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger btn-xs" %></td>
                <% end % %>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
</div>

app/views/contents/update.js.erb
<%= render "save" %>