config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    match '/users/:id', :to => 'users#show',    :as => :user,         :via => :get
    match '/users', :to => 'users#index',    :as => :users,         :via => :get
    match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete

    resources :students
    resources :student_responses, only: [:create,:new]
    # resources :tags, except: [:show]
    resources :contents, except: [:index, :show]

    get 'tags/:tag', to: 'static_pages#home', as: 'tugg'

    root :to => "static_pages#home"

    get 'users/:id/contents/summary_index', to: 'contents#summary_index', as: "summary_index"

    match '/help', to: "static_pages#help", via: 'get'
    match '/about', to: "static_pages#about", via: 'get'
    match '/contact', to: "static_pages#contact", via: 'get'

    get 'students/:id/show_response' => "students#show_response", as: "show_response"
    get 'students/:id/show_summary' => "students#show_summary", as: "show_summary"
    get 'students/:id/show_selected' => "students#show_selected", as: "show_selected"

    match '/sign_in_guest', to: "application#create_guest_user", via: 'get'

end

app/models/student.rb
class Student < ActiveRecord::Base
    belongs_to :user
    has_many :student_responses, :dependent => :destroy

    validates :name, :presence => true
    scope :sorted_name,   ->   { order('name ASC') }

    def to_csv(options = {})
        CSV.generate(options) do |csv|
            csv << ['Image ID', 'Recorded Emotion', 'Matched', 'Possible Answers' ]
            self.student_responses.each do |response|
                csv << [response.matched_image_id, response.emotion, response.response_correct_as_string, response.possible_answers]
            end
        end
    end

    def dates
        results = self.student_responses.group("date(created_at)").count.keys
        return results.sort!
    end

    def percentages

        total_responses_by_day = self.student_responses.group("date(student_responses.created_at)").
                            select("student_responses.created_at").count
        responses_by_day = self.student_responses.group("date(student_responses.created_at)").group(:correct).count

        results = Array.new

        responses_by_day.sort_by{|k,v| k[0]}.each do |resp|
            correctness = resp[0][1]
            this_date = resp[0][0]
            summary = resp[1]

            summ = total_responses_by_day.fetch(this_date).to_f
            to_insert = ((summary.to_f / summ) * 100.0).floor

            if to_insert == 100
                if correctness
                    results << {:unit => this_date, :status => "Correct", :val => to_insert}
                    results << {:unit => this_date, :status => "Not correct", :val => (100 - to_insert)}
                else
                    results << {:unit => this_date, :status => "Correct", :val => (100 - to_insert)}
                    results << {:unit => this_date, :status => "Not correct", :val => to_insert}
                end
            else
                if correctness
                    results << {:unit => this_date, :status => "Correct", :val => to_insert}
                    results << {:unit => this_date, :status => "Not correct", :val => (100.0 - to_insert)}
                else
                    # results << {:unit => this_date, :status => "Correct", :val => (to_insert-100)}
                    # results << {:unit => this_date, :status => "Not correct", :val => to_insert}

                end
            end

        end

        return results

    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
            :recoverable, :rememberable, :trackable, :validatable

    has_many :contents, :dependent => :destroy
    has_many :tags
    has_many :students, :dependent => :destroy

    validates :email, :presence => true, :uniqueness => true

    def guest?
        self.guest
    end

    def admin?
        self.admin
    end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    respond_to :html, :js, :json
    before_action :set_student, only: [:show, :edit, :update, :destroy, :show_response, :show_summary, :show_graph, :show_chart, :show_selected]
    helper_method :sort_column, :sort_direction

    def index
        @students = Student.where(:user_id => current_user.id).sorted_name
    end

    def show_summary
        @responses = @student.student_responses.order(sort_column + ' ' + sort_direction)
        params[:datas] = @student.percentages.to_json
        respond_to do |format|
            format.html
            format.json { render json: params[:datas] }
            format.csv { send_data @student.to_csv}
            format.xls { send_data @student.to_csv(col_sep: "\t") }
        end
    end

    def show
        session[:current_student] = Hash.new
        session[:current_student] = @student.id
        respond_to do |format|
            format.html
        end
    end

    def show_selected
        @selected_contents = Content.joins(:tags).
                                    where(tags: { id: params[:tag_ids]}).
                                    belongs_to_user(current_user.id).distinct
        respond_to do |format|
            format.js
        end
    end

    def show_response
        @student_response = @student.student_responses.build
        respond_to do |format|
            format.js
        end
    end

    def new
        @student = current_user.students.new(params[:student])
        respond_to do |format|
            format.html { render :layout => false }
        end
    end

    def edit
        @student = Student.find(params[:id])
    end

    def create
        @student = current_user.students.build(student_params)
        if @student.save
            respond_to do |format|
                format.html { redirect_to :back }
                format.js { render :js => "window.location = 'students'" }
            end
        else
            flash[:danger] = "boo"
        end
    end

    def update
        respond_to do |format|
            if @student.update(student_params)
                format.html { redirect_to students_url }
                format.js { render :js => "window.location = 'students'" }
            else
                format.html { render :edit }
                format.json { render json: @student.errors, status: :unprocessable_entity }
                format.js
            end
        end
    end

    def destroy
        @student.destroy
        respond_to do |format|
            format.html { redirect_to students_url, notice: "Student's record was successfully destroyed." }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
        def set_student
            @student = Student.find(params[:id])
        end

    # Never trust parameters from the scary internet, only allow the white list through.
        def student_params
            params.require(:student).permit(:name)
        end

        def sort_column
            @student.student_responses.column_names.include?(params[:order_to_sort_by]) ? params[:order_to_sort_by] : "created_at"
        end

        def sort_direction
            %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
        end
end

app/views/students/_contents_form.html.erb
<h3> Selecting emotions </h3>
<% tag_selection Content.select_tags(current_user.id) do |tag| %>
    <li>
        <%= check_box_tag "tag_ids[]", tag.id, false, class: 'submittable' %>
        <%= tag.tagname %>
    </li>
<% end %>
<br/>
<%= link_to "Select", show_selected_path(@student), remote: true, class: "btn btn-primary btn-xs btn-style submitme" %>

app/views/students/_form.html.erb
<%= form_for(@student, :remote => true) do |f| %>
    <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary btn-xs" %>
    </div>
<% end %>

app/views/students/_new.html.erb
<h1> Hello </h1>
<%= render 'form' %>

app/views/students/_student.html.erb
<tr>
    <td>
        <%= link_to student do %>
            Start test for <span class="student-name"> <%= student.name %> </span>
        <% end %>
    </td>

    <td class="col-sm-2"><%= link_to 'Show summary', show_summary_path(student) %></td>
    <td class="col-sm-1"> <%= link_to 'Edit', edit_student_path(student), remote: true, class: "btn btn-primary btn-xs btn-style" %></td>
    <td class="col-sm-1"> <%= link_to 'Del', student, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs btn-style" %></td>

</tr>

<div id="student-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" area-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" align="center">Editing student</h4>
            </div>
            <div class="modal-body" id="student-modal-body">
            </div>
            <div class="modal-footer">
                <div class="row text-center">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/create.js.erb
<% if @student.valid? %>

    $(".js-students").prepend("<%= escape_javascript(render(@student)) %>");

<% else %>

    $("#tabs-errors").html("<%= escape_javascript(render 'shared/messages', object: @student) %>");

    removeErrorExplanation();

<% end %>

app/views/students/edit.js.erb
$("#student-modal-body").html("<%= escape_javascript(render 'form') %>")
$("#student-modal").modal("show")

app/views/students/index.html.erb
<div id="tabs">
    <ul>
        <li><a href="#tabs-1" class="remove_me">Students:</a></li>
        <li><%= link_to "Add a student", new_student_path, :remote => true, :class => "remove_me" %></li>
    </ul>
    <div id="tabs-2"></div>
    <div id="tabs-errors"></div>
    <div id="tabs-1">
        <div class = "js-students">
            <div class="row">
                <div class = "col-sm-10 col-sm-offset-1" >
                    <table class="table table-striped">
                        <thead>
                            <tr>
                              <th>Name</th>
                              <th colspan="4"></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% if !@students.nil? %>
                                <%= render @students %>
                            <% end %>
                        </body>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/new.html.erb
<h3>New student</h3>
<div class="row">
    <div class="col-md-3">
        <%= render 'form' %>
    </div>
</div>

app/views/students/new.js.erb
$('#new_student_link').hide().after('');

app/views/students/show.html.erb
<p> <span class="student-name"><%= @student.name %></span>
    &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;
    <%= link_to 'Show summary', show_summary_path(@student) %>
    &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;
    <%= link_to 'Back to all', students_path %>
</p>

<br />
<div id="student-tabs">
    <ul>
        <li><a href="#test-tabs" class='test-tabs-button'>Test</a></li>
        <li> <a href ='#emotion-tabs'> Select emotions</a></li>
    </ul>

    <div id="test-tabs">
        <%= render 'blank_response' %>
    </div>

    <div id="emotion-tabs">
        <%= render 'contents_form' %>
    </div>
</div>

<div id="dialog-wrong" title="Oh my!">
    <p> Sorry! Not quite there. :((. </p>
</div>
<div id="dialog-correct" title="Oh joy!">
    <p> Yippetteee! Happy dance! :)). </p>
</div>

app/views/students/show_response.js.erb
$("#student_response").html("<%= escape_javascript(render(:partial => 'shared/student_response_form')) %>");

$('.submitanswer').on('click',function(){
    $.ajax({
        complete: function(){
            $('.new_student_response').each(function()
            {
                this.reset();
            });
        }
    });
});

app/views/students/show_selected.js.erb
<% if @selected_contents.count <= 0 %>
    $("#test-tabs").html("<%= escape_javascript(render 'blank_response') %>");
<% else %>
    $("#test-tabs").html("<%= escape_javascript(render 'shared/selected_contents') %>");
    var message =  "<div class='message'><p><br />Thank you for making your selection! Please click on the 'Test' tab now.</p></div>";
    $("#emotion-tabs").prepend($(message));
<% end %>

$('#myCarousel').on('slid.bs.carousel', function () {
    createResponseForm();
});

app/views/students/show_summary.html.erb
<p class="pull-right">
    <%= link_to @student do %>
        <span class="student-name"> Start test </span>
    <% end %>
    &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp;
    <%= link_to students_path do %>
        <span class="student-name"> Back to all </span>
    <% end %>
</p>
<p>
    Download: &nbsp;&nbsp;
    <%= link_to show_summary_path(format: "csv") do %>
        <span class="student-name"> CSV </span>
    <% end %>
    &nbsp;&nbsp; | &nbsp;&nbsp;
    <%= link_to show_summary_path(format: "xls") do %>
        <span class="student-name"> Excel </span>
    <% end %>
</p>
<br />
<p>
    <%= link_to "Show Graph", {:datas => "datas"}, {id: "show_graph", class: 'btn btn-default btn-sm'} %>
</p>
<br />

<div id="responses_chart"></div>

<table class='table table-striped text-center'>
    <thead>
        <tr >
            <th class="text-center"> <%= sortable "created_at", "Date" %> </th>
            <th class="text-center"> <%= sortable "emotion", "Emotions" %> </th>
            <th class="text-center">Matched</th>
            <th class="text-center">Possible Answers</th>
            <th class="text-center">Associated Image ID</th>
        </tr>
    </thead>
    <tbody>
        <% @responses.each do |response| %>
          <tr>
            <td><%= l response.created_at, :format => :date_format %></td>
            <td><%= response.emotion %></td>
            <td><%= response.response_correct_as_string %></td>
            <td><%= response.possible_answers %></td>
            <% if !response.matched_image_id.blank? %>
                <td><%= response.matched_image_id %></td>
            <% else %>
                <td>Image deleted from the database by owner</td>
            <% end %>
          </tr>
        <% end %>
    </tbody>
</table>
<br>

app/views/students/update.js.erb
<% if @student.errors.any? %>
    $("#student-modal-body").prepend("<%= escape_javascript(render 'shared/messages', object: @student) %>");
<% else %>
    $("#student-modal").modal("hide");
<% end %>