config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    match '/users/:id', :to => 'users#show',    :as => :user,         :via => :get
    match '/users', :to => 'users#index',    :as => :users,         :via => :get
    match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete

    resources :students
    resources :student_responses, only: [:create,:new]
    # resources :tags, except: [:show]
    resources :contents, except: [:index, :show]

    get 'tags/:tag', to: 'static_pages#home', as: 'tugg'

    root :to => "static_pages#home"

    get 'users/:id/contents/summary_index', to: 'contents#summary_index', as: "summary_index"

    match '/help', to: "static_pages#help", via: 'get'
    match '/about', to: "static_pages#about", via: 'get'
    match '/contact', to: "static_pages#contact", via: 'get'

    get 'students/:id/show_response' => "students#show_response", as: "show_response"
    get 'students/:id/show_summary' => "students#show_summary", as: "show_summary"
    get 'students/:id/show_selected' => "students#show_selected", as: "show_selected"

    match '/sign_in_guest', to: "application#create_guest_user", via: 'get'

end

app/models/tag.rb
class Tag < ActiveRecord::Base

    has_many :taggings
    has_many :contents, through: :taggings
    has_many :student_responses, through: :taggings
    belongs_to :user
    validates :tagname, :presence => true

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

    before_action :set_tag, only: [:edit, :update, :destroy]

    def index
        @tags = Tag.all
    end

    def new
        @tag = Tag.new
    end

    def edit
    end

    def create
        @tag = Tag.new(tag_params)
        respond_to do |format|
            if @tag.save
                format.html { redirect_to :back }
            else
                format.html { render :new }
                format.json { render json: @tag.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @tag.update(tag_params)
                format.js { render layout: false }
            else
                format.html { render :edit }
                format.json { render json: @tag.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @tag.destroy
        respond_to do |format|
            format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
        def set_tag
            @tag = Tag.find(params[:id])
        end
    # Never trust parameters from the scary internet, only allow the white list through.
        def tag_params
            params.require(:tag).permit(:tagname, :selected)
        end
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tagname %><br>
    <%= f.text_field :tagname %>
  </div>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :content_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/_tag.html.erb
<span class='tag'><%= tag.tagname %></span>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <thead>
    <tr>
      <th>Tagname</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.tagname %></td>
        <td><%= tag.selected %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tagname:</strong>
  <%= @tag.tagname %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tag.selected %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>

app/views/tags/update.js.erb
<% if @tag.errors.any? %>
    // nothing
<% else %>
    $("#tag_modal").modal("hide");
<% end %>

app/views/tags/update_delte.js.erb
<% if @tag.errors.any? %>
    // $("#student-modal-body").prepend("<%#= escape_javascript(render 'shared/messages', object: @student) %>");
<% else %>
    // $('.submitme2').on('click', function(){
        // $('#edit_tag_37').trigger('submit.rails');
    // });

    $("#tag_modal").modal("hide");

<% end %>