config/routes.rb
Rails.application.routes.draw do

    devise_for :users
    match '/users/:id', :to => 'users#show',    :as => :user,         :via => :get
    match '/users', :to => 'users#index',    :as => :users,         :via => :get
    match '/users/:id', :to => 'users#destroy', :as => :destroy_user, :via => :delete

    resources :students
    resources :student_responses, only: [:create,:new]
    # resources :tags, except: [:show]
    resources :contents, except: [:index, :show]

    get 'tags/:tag', to: 'static_pages#home', as: 'tugg'

    root :to => "static_pages#home"

    get 'users/:id/contents/summary_index', to: 'contents#summary_index', as: "summary_index"

    match '/help', to: "static_pages#help", via: 'get'
    match '/about', to: "static_pages#about", via: 'get'
    match '/contact', to: "static_pages#contact", via: 'get'

    get 'students/:id/show_response' => "students#show_response", as: "show_response"
    get 'students/:id/show_summary' => "students#show_summary", as: "show_summary"
    get 'students/:id/show_selected' => "students#show_selected", as: "show_selected"

    match '/sign_in_guest', to: "application#create_guest_user", via: 'get'

end

app/views/layouts/_footer.html.erb
<div class="footer">
    <div class="container">
        <small>
            <%= link_to "About", about_path %>
        </small>
        <nav>
            <ul>
                <li><%= link_to "Contact", contact_path %></li>
                <li><%= link_to "Help", help_path %></li>
            </ul>
        </nav>
    </div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <% if user_signed_in? %>
                <% if current_user.guest? %>
                    <a class="navbar-brand" href="#">Logged in as Guest</a>
                <% else %>
                    <a class="navbar-brand" href="#">Logged in as <%= current_user.email %></a>
                <% end %>
            <% else %>
                <%= link_to "SPEECHY", root_path, class: "navbar-brand" %>
            <% end %>
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav pull-right">
                <li><%= link_to "Home", root_path %></li>
                <% if user_signed_in? %>
                    <% if current_user.admin? %>
                        <li><%= link_to 'Users', users_path %></li>
                    <% end %>
                    <li><%= link_to 'Upload', new_content_path, remote: true %></li>
                    <li><%= link_to 'Students', students_path, "data-no-turbolink" => true %></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <% if current_user.guest? %>
                                <%= render 'static_pages/edit_links' %>
                            <% else %>
                                <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                                <%= render 'static_pages/edit_links' %>
                            <% end %>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Login", new_user_session_path %></li>
                    <li><%= link_to "Sign up", new_user_registration_path %></li>
                <% end %>
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<div id="content-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" area-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" align="center" id="content-modal-title"></h4>
            </div>
            <div class="modal-body" id="modal-body">
            </div>
            <div class="modal-footer">
                <div class="row text-center">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_layout_messages.html.erb
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

        <title><%= full_title(yield(:title)) %></title>
        <%= stylesheet_link_tag    'application', media: 'all' %>
        <%= javascript_include_tag 'application' %>
        <%= csrf_meta_tags %>
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
</head>
<body onunload="">

    <%= render 'layouts/header' %>
    <div class="container">
        <%= render "layouts/layout_messages" %>
        <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>

</body>
</html>